-- Schema do SGV. Espelha as entidades JPA da sgv-api — ao mexer em uma
-- @Entity, mexa aqui também.

\set ON_ERROR_STOP on

-- As tabelas passam a pertencer a sgv_ddl, não ao superusuário que roda o
-- script. É o que faz o ALTER DEFAULT PRIVILEGES de 04 valer.
SET ROLE sgv_ddl;

CREATE TABLE IF NOT EXISTS destino (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   VARCHAR(255) NOT NULL,
  cidade VARCHAR(255) NOT NULL,
  pais   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS area (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  CONSTRAINT uk_area_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS colaborador (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula VARCHAR(255) NOT NULL,
  nome      VARCHAR(255) NOT NULL,
  CONSTRAINT uk_colaborador_matricula UNIQUE (matricula),
  -- Regra da especificação, garantida também no banco.
  CONSTRAINT ck_colaborador_matricula
    CHECK (matricula ~ '^[0-9]{4}-[0-9]$')
);

-- Área e cargo do colaborador ao longo do tempo. `fim` nulo = vigente.
-- Uma viagem aponta para a lotação que valia quando foi solicitada, e por isso
-- continua correta depois de a pessoa mudar de área ou de cargo.
CREATE TABLE IF NOT EXISTS colaborador_lotacao (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colaborador_id BIGINT       NOT NULL,
  area_id        BIGINT       NOT NULL,
  cargo          VARCHAR(255) NOT NULL,
  inicio         TIMESTAMP    NOT NULL,
  fim            TIMESTAMP,
  CONSTRAINT fk_lotacao_colaborador
    FOREIGN KEY (colaborador_id) REFERENCES colaborador (id) ON DELETE CASCADE,
  CONSTRAINT fk_lotacao_area
    FOREIGN KEY (area_id) REFERENCES area (id),
  CONSTRAINT ck_lotacao_cargo
    CHECK (cargo IN ('COLABORADOR', 'GESTOR')),
  CONSTRAINT ck_lotacao_periodo
    CHECK (fim IS NULL OR fim >= inicio)
);

-- No máximo uma lotação vigente por colaborador — a regra que o
-- Colaborador.lotar() mantém em Java, garantida também aqui.
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotacao_vigente
  ON colaborador_lotacao (colaborador_id) WHERE fim IS NULL;
CREATE INDEX IF NOT EXISTS ix_lotacao_colaborador
  ON colaborador_lotacao (colaborador_id, inicio);
CREATE INDEX IF NOT EXISTS ix_lotacao_area ON colaborador_lotacao (area_id);

-- Migração: a área era uma coluna de texto em colaborador. Em bancos que já
-- existiam, promove cada valor distinto a uma linha de `area` e troca a coluna
-- pela FK. Em banco novo o CREATE TABLE acima já nasce certo e o bloco não faz
-- nada.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema = 'public'
                AND table_name = 'colaborador'
                AND column_name = 'area') THEN

    ALTER TABLE colaborador ADD COLUMN IF NOT EXISTS area_id BIGINT;

    INSERT INTO area (nome)
    SELECT DISTINCT area FROM colaborador
    ON CONFLICT (nome) DO NOTHING;

    UPDATE colaborador c
       SET area_id = a.id
      FROM area a
     WHERE a.nome = c.area;

    ALTER TABLE colaborador DROP COLUMN area;
    ALTER TABLE colaborador ALTER COLUMN area_id SET NOT NULL;
    ALTER TABLE colaborador
      ADD CONSTRAINT fk_colaborador_area FOREIGN KEY (area_id) REFERENCES area (id);
  END IF;
END $$;

-- Migração: área e cargo saíram de colaborador e viraram colaborador_lotacao.
-- Os valores atuais viram a primeira lotação, aberta agora — não há como saber
-- desde quando valiam, e inventar uma data anterior seria forjar histórico.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema = 'public'
                AND table_name = 'colaborador'
                AND column_name = 'area_id') THEN

    INSERT INTO colaborador_lotacao (colaborador_id, area_id, cargo, inicio)
    SELECT id, area_id, cargo, now() FROM colaborador;

    -- DROP COLUMN leva junto a FK e o índice que dependiam dela.
    ALTER TABLE colaborador DROP COLUMN cargo;
    ALTER TABLE colaborador DROP COLUMN area_id;
  END IF;
END $$;

-- Migração: colaborador ganhou `cargo`. Quem já existia entra como
-- COLABORADOR — promover a GESTOR é decisão de negócio, não de migração.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema = 'public'
                AND table_name = 'colaborador'
                AND column_name = 'area_id')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                      WHERE table_schema = 'public'
                        AND table_name = 'colaborador'
                        AND column_name = 'cargo') THEN

    ALTER TABLE colaborador ADD COLUMN cargo VARCHAR(255);
    UPDATE colaborador SET cargo = 'COLABORADOR' WHERE cargo IS NULL;
    ALTER TABLE colaborador ALTER COLUMN cargo SET NOT NULL;
    ALTER TABLE colaborador
      ADD CONSTRAINT ck_colaborador_cargo CHECK (cargo IN ('COLABORADOR', 'GESTOR'));
  END IF;
END $$;

-- Migração: a matrícula passou a ter formato fixo (XXXX-X, só dígitos). O
-- CHECK só entra depois que os dados estiverem no formato — se houver linha
-- fora, o script para e diz quantas são, em vez de falhar com erro de
-- constraint sem contexto.
DO $$
DECLARE
  fora_do_formato BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'ck_colaborador_matricula') THEN

    SELECT count(*) INTO fora_do_formato
      FROM colaborador WHERE matricula !~ '^[0-9]{4}-[0-9]$';

    IF fora_do_formato > 0 THEN
      RAISE EXCEPTION
        'ha % colaborador(es) com matricula fora do formato XXXX-X. '
        'Liste com: SELECT id, matricula FROM colaborador '
        'WHERE matricula !~ ''^[0-9]{4}-[0-9]$'';', fora_do_formato;
    END IF;

    ALTER TABLE colaborador
      ADD CONSTRAINT ck_colaborador_matricula CHECK (matricula ~ '^[0-9]{4}-[0-9]$');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS viagem (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destino_id      BIGINT       NOT NULL,
  colaborador_id  BIGINT       NOT NULL,
  motivo          VARCHAR(255) NOT NULL,
  data_saida      DATE         NOT NULL,
  data_retorno    DATE         NOT NULL,
  meio_transporte VARCHAR(255) NOT NULL,
  situacao        VARCHAR(255) NOT NULL,
  motivo_ajuste   VARCHAR(500),
  -- Nula até a viagem ser solicitada; rascunho não é solicitação.
  lotacao_id      BIGINT,
  CONSTRAINT fk_viagem_destino
    FOREIGN KEY (destino_id) REFERENCES destino (id),
  CONSTRAINT fk_viagem_colaborador
    FOREIGN KEY (colaborador_id) REFERENCES colaborador (id),
  CONSTRAINT fk_viagem_lotacao
    FOREIGN KEY (lotacao_id) REFERENCES colaborador_lotacao (id),
  -- Regras da especificação, garantidas também no banco.
  CONSTRAINT ck_viagem_periodo
    CHECK (data_retorno >= data_saida),
  CONSTRAINT ck_viagem_situacao
    CHECK (situacao IN ('RASCUNHO', 'SOLICITADA', 'EM_AJUSTE',
                        'APROVADA', 'REJEITADA', 'CANCELADA')),
  CONSTRAINT ck_viagem_meio_transporte
    CHECK (meio_transporte IN ('AEREO', 'RODOVIARIO', 'FERROVIARIO',
                               'VEICULO_PROPRIO', 'OUTRO'))
);

-- Colunas usadas pelos filtros da tela de viagens e do dashboard.
CREATE INDEX IF NOT EXISTS ix_viagem_destino     ON viagem (destino_id);
CREATE INDEX IF NOT EXISTS ix_viagem_colaborador ON viagem (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_viagem_situacao    ON viagem (situacao);

-- Migração: o fluxo de aprovação trouxe EM_AJUSTE e CANCELADA, e o texto do
-- que o gestor mandou ajustar. Drop + add deixa o bloco re-executável.
ALTER TABLE viagem ADD COLUMN IF NOT EXISTS motivo_ajuste VARCHAR(500);
ALTER TABLE viagem DROP CONSTRAINT IF EXISTS ck_viagem_situacao;
ALTER TABLE viagem ADD  CONSTRAINT ck_viagem_situacao
  CHECK (situacao IN ('RASCUNHO', 'SOLICITADA', 'EM_AJUSTE',
                      'APROVADA', 'REJEITADA', 'CANCELADA'));

-- Migração: a viagem passa a apontar para a lotação de quem a solicitou.
-- Fica nula nas viagens já existentes: qual lotação valia quando foram
-- solicitadas é informação que não temos, e chutar seria inventar histórico.
ALTER TABLE viagem ADD COLUMN IF NOT EXISTS lotacao_id BIGINT;
ALTER TABLE viagem DROP CONSTRAINT IF EXISTS fk_viagem_lotacao;
ALTER TABLE viagem ADD  CONSTRAINT fk_viagem_lotacao
  FOREIGN KEY (lotacao_id) REFERENCES colaborador_lotacao (id);
CREATE INDEX IF NOT EXISTS ix_viagem_lotacao ON viagem (lotacao_id);

-- Uma linha por mudança de situação, inclusive a criação. Nunca é atualizada:
-- é registro de auditoria. ON DELETE CASCADE porque excluir só é permitido em
-- RASCUNHO — o histórico some junto com a viagem que nunca foi submetida.
CREATE TABLE IF NOT EXISTS viagem_historico (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viagem_id      BIGINT       NOT NULL,
  situacao       VARCHAR(255) NOT NULL,
  responsavel_id BIGINT       NOT NULL,
  lotacao_id     BIGINT,
  registrado_em  TIMESTAMP    NOT NULL,
  observacao     VARCHAR(500),
  CONSTRAINT fk_viagem_historico_viagem
    FOREIGN KEY (viagem_id) REFERENCES viagem (id) ON DELETE CASCADE,
  CONSTRAINT fk_viagem_historico_responsavel
    FOREIGN KEY (responsavel_id) REFERENCES colaborador (id),
  CONSTRAINT fk_viagem_historico_lotacao
    FOREIGN KEY (lotacao_id) REFERENCES colaborador_lotacao (id),
  CONSTRAINT ck_viagem_historico_situacao
    CHECK (situacao IN ('RASCUNHO', 'SOLICITADA', 'EM_AJUSTE',
                        'APROVADA', 'REJEITADA', 'CANCELADA'))
);

CREATE INDEX IF NOT EXISTS ix_viagem_historico_viagem
  ON viagem_historico (viagem_id, registrado_em);

-- Migração: o histórico passa a congelar também a lotação de quem agiu.
-- Nula nos registros anteriores, pelo mesmo motivo das viagens antigas.
ALTER TABLE viagem_historico ADD COLUMN IF NOT EXISTS lotacao_id BIGINT;
ALTER TABLE viagem_historico DROP CONSTRAINT IF EXISTS fk_viagem_historico_lotacao;
ALTER TABLE viagem_historico ADD  CONSTRAINT fk_viagem_historico_lotacao
  FOREIGN KEY (lotacao_id) REFERENCES colaborador_lotacao (id);

RESET ROLE;
