-- Schema do SGV. Espelha as entidades JPA da sgv-api — ao mexer em uma
-- @Entity, mexa aqui também.

\set ON_ERROR_STOP on

-- As tabelas passam a pertencer a sgv_ddl, não ao superusuário que roda o
-- script. É o que faz o ALTER DEFAULT PRIVILEGES de 04 valer.
SET ROLE sgv_ddl;

CREATE TABLE IF NOT EXISTS destino (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   VARCHAR(255) NOT NULL,
  cidade VARCHAR(255) NOT NULL,
  pais   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS colaborador (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula VARCHAR(255) NOT NULL,
  nome      VARCHAR(255) NOT NULL,
  area      VARCHAR(255) NOT NULL,
  CONSTRAINT uk_colaborador_matricula UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS viagem (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destino_id      BIGINT       NOT NULL,
  colaborador_id  BIGINT       NOT NULL,
  motivo          VARCHAR(255) NOT NULL,
  data_saida      DATE         NOT NULL,
  data_retorno    DATE         NOT NULL,
  meio_transporte VARCHAR(255) NOT NULL,
  situacao        VARCHAR(255) NOT NULL,
  CONSTRAINT fk_viagem_destino
    FOREIGN KEY (destino_id) REFERENCES destino (id),
  CONSTRAINT fk_viagem_colaborador
    FOREIGN KEY (colaborador_id) REFERENCES colaborador (id),
  -- Regras da especificação, garantidas também no banco.
  CONSTRAINT ck_viagem_periodo
    CHECK (data_retorno >= data_saida),
  CONSTRAINT ck_viagem_situacao
    CHECK (situacao IN ('RASCUNHO', 'SOLICITADA', 'APROVADA', 'REJEITADA')),
  CONSTRAINT ck_viagem_meio_transporte
    CHECK (meio_transporte IN ('AEREO', 'RODOVIARIO', 'FERROVIARIO',
                               'VEICULO_PROPRIO', 'OUTRO'))
);

-- Colunas usadas pelos filtros da tela de viagens e do dashboard.
CREATE INDEX IF NOT EXISTS ix_viagem_destino     ON viagem (destino_id);
CREATE INDEX IF NOT EXISTS ix_viagem_colaborador ON viagem (colaborador_id);
CREATE INDEX IF NOT EXISTS ix_viagem_situacao    ON viagem (situacao);

RESET ROLE;
